coverage:
  status:
    project: # Measures overall project coverage.
      target: auto
      threshold: 0.05%
      informational: true # Patch coverage for stats only.
    patch: #  Only measures lines adjusted in the pull request.
      target: auto
      threshold: 0.05%
      informational: true # Patch coverage for stats only.
